Added set of filter parameters for products
iov42/version-2-apispec pull request #17
Opened 2023-04-21 09:21 UTC by davidiov42

I have added the filters on the Product endpoint.

2023-04-24 19:54 UTC, krisrimar-iov42 commented on openapi/paths/products.yml
>      - $ref: '../components/parameters/query/name.yml'
@davidiov42 so the product name query is an array, so I assume I can get multiple products by names. I assume it is working as RegExp by matching character combinations in names. But would that be a plausible case? (i.e. providing multiple strings to match the product names against) I would rather include an "Ids" parameter, where users can provide an array of specific product IDs they want to receive (refer to PayPal API: https://developer.paypal.com/docs/api/subscriptions/v1/#plans_list), and make the "name" field a single string value.

I also would include "sort_by" parameter, which would allow sorting products by names (for now just names) and a "sort_order" parameter allowing to sort either in ASC or DESC order.

Maybe @da-web you can give some guidance on "name" search and "specific IDs" search.

2023-04-25 07:27 UTC, da-web commented on openapi/paths/products.yml
>      - $ref: '../components/parameters/query/name.yml'
@krisrimar-iov42 Why do you assume it is a regex filter? I hope not - the most flexible pattern you should use is just a simple wildcard search - and that should be used wisely and sparingly. But when I see an array of filter parameters I would not expect wildcard searches at all but rather full matches (any).

rg. sorting: spring does support the following variant out of the box in the query:  eg. sort=name,desc

2023-04-26 09:56 UTC, krisrimar-iov42 commented on openapi/paths/products.yml
>      - $ref: '../components/parameters/query/name.yml'
@da-web thanks for correcting. It was mostly to prompt @davidiov42 to consider whether it should be an array of names or rather just one name, but with wildcard search. Otherwise the search will be very painful, if the user needs to be very precise (unless we query products on the UI and auto-suggest, so that the user can just select one)... but then that is a search by ID.

2023-05-02 08:59 UTC, davidiov42 commented on openapi/paths/products.yml
>      - $ref: '../components/parameters/query/name.yml'
Mmm I would possibly consider "startswith" ... that seems like a typical filtering option?

2023-05-02 10:54 UTC, davidiov42 commented on openapi/paths/products.yml
>      - $ref: '../components/parameters/query/name.yml'
However we decide to implement this in the back end, the parameters shouldn't change. This should do for now.

2023-05-11 09:19 UTC, krisrimar-iov42 requested changes
@davidiov42 just one change still required: _parameters/query/unit-type.yml_ is still an array and not just a string like all the rest.

2023-05-11 14:41 UTC, krisrimar-iov42 commented on openapi/components/parameters/query/base-unit.yml
> +  minItems: 1
@davidiov42 does this mean I have to provide at least one item for the query? Or I can still provide none if I wish to just get all Products?

2023-05-11 14:55 UTC, krisrimar-iov42 approved these changes

2023-05-16 12:11 UTC, merged