Updated locations and location links. Links are now first class citizens
iov42/version-2-apispec pull request #19
Opened 2023-04-24 13:47 UTC by davidiov42

2023-04-27 11:27 UTC, krisrimar-iov42 commented on openapi/components/schemas/location.yml
@davidiov42 is not shown in the PR, but the address "id" parameter should be removed.

2023-04-27 11:46 UTC, krisrimar-iov42 commented on openapi/components/schemas/location.yml
@davidiov42 if we are including Geo data into the model of the location, we have to then realize the fact that we are tying ourselves into one format - GeoJSON. so if our users have .shp (Shapefile), KML, GeoTIFF, GML they will have to convert them to Geo JSON (which shouldn't be a lot of work at all, as it seems all of them, at the end of the day, are just sequenced arrays of GPS coordinates).

In any case, the model you currently have is:

```
{
"type": "GeometryCollection",
    "geometries": [
      {
        "type": "Point"
      }
    ]
}
```

the main part `coordinates` is missing, but I think we should limit the API specs to stating that it has to be a JSON file following GeoJSON standard, and that we only support geometry types of "Point" and "Polygon". In any case, looking at https://geojson.org/ I cannot see mentions `GeometryCollection`, as you have suggested in the parameter description, but maybe the docs are outdated.

2023-04-27 11:53 UTC, krisrimar-iov42 commented on openapi/components/schemas/location.yml
@davidiov42 in the `location` model - what determines which organisation / connection the location belongs to? Not talking about which org. that location is "stored" with, but rather "is this my own location? is this a location with no 'external organisation' (connection) associated with it? is there an `external organisation` (connection) associated with it?"

2023-04-27 11:57 UTC, krisrimar-iov42 commented on openapi/paths/locationLinks.yml
> +              - $ref: '../components/schemas/id.yml'
@davidiov42 no need to include link `id` in POST

2023-04-27 12:10 UTC, krisrimar-iov42 commented on openapi/components/schemas/locationLink.yml
> +  by:
@davidiov42 should be excluded from POST request, as this will be determined by the system (i.e. I cannot specify another organisation when linking my own locations)

But as a separate question: how does this model support linking two locations in different organisations? Will users just add those location URIs into the add link request? Or will this be a separate request? But then we need to have smth like "link status" (the accepting org has to accept the linking request)

2023-04-27 13:09 UTC, krisrimar-iov42 commented on openapi/paths/locationLink.yml
>    description: Update link by id
@davidiov42 is there a point in the update endpoint? I would probably limit links to just POST and DELETE, as if a user made a mistake in a link, they would most likely just delete it and create a new one, instead of updating an existing one.

Unless we plan to enrich links with some additional parameters (but I can't think of any).

2023-04-27 15:00 UTC, davidiov42 commented on openapi/components/schemas/location.yml
so I think location association is done through attachments ....

2023-04-27 15:02 UTC, davidiov42 commented on openapi/components/schemas/location.yml
I think it's good to pick one standard ... the reason GEOJSON makes sense is that it is Json format. As you said I think we get people to convert, in time we may be able to allow people to convert within our app

2023-05-02 09:27 UTC, davidiov42 commented on openapi/paths/locationLink.yml
>    description: Update link by id
I guess the only additional parameter would be a description for the link...

2023-05-02 11:05 UTC, davidiov42 commented on openapi/components/schemas/locationLink.yml
> +  by:
Will remove from Post

2023-05-02 12:44 UTC, davidiov42 commented on openapi/paths/locationLink.yml
>    description: Update link by id
Have removed the PUT for location links

2023-05-03 10:15 UTC, krisrimar-iov42 requested changes
Following changes are still needed:

**Locations**

- Remove `id` parameter from `address` of location (both POST and GET);
- **GET /locations** should return `id` parameter for each location (but please make sure that GET /locations/{locationId} does not include it);

**Links**

- Remove `by` from POST /organisations/{orgId}/location-links (will be system-determined + I think we first need to fully grasp how this will work when data is transferred to another org. before adding it to specs);
- Remove `when` from POST /organisations/{orgId}/location-links (should only be present in GET request);
- Provide means to query all links of a particular location(s);

2023-05-03 10:56 UTC, davidiov42 commented
Implemented these changes ... except the pattern of id in GET's is consistently there in everything.

2023-05-08 14:18 UTC, krisrimar-iov42 commented on openapi/paths/locationLinks.yml
> +              - $ref: '../components/schemas/locationLink.yml'
@davidiov42 your add location link request requires the user to specify `locationAURI` and `locationBURI`, but it is made through the endpoint `POST /organisations/{orgId}/locations/{locId}/links` (the `locId` part already contains the `locationA` part.

I would suggest having links separate from the `locations` endpoint - then we can create any A/B combinations. Otherwise, nothing prevents me from using the `POST /organisations/{orgId}/locations/A/links` endpoint to create a link between location B and C.

2023-05-08 14:29 UTC, krisrimar-iov42 commented on openapi/paths/locationLinks.yml
> +              - $ref: '../components/schemas/locationLink.yml'
Also, `date` should be removed from POST request and probably renamed to `when` for consistency, but I much prefer the term `createdTime` or `createdAt`, as `when` is a bit ambiguous.

And `status` should be removed from the model altogether.

2023-05-08 14:32 UTC, krisrimar-iov42 commented on openapi/paths/locationLinks.yml
> +              - $ref: '../components/schemas/id.yml'
@davidiov42 please remove from POST.

2023-05-16 12:46 UTC, krisrimar-iov42 approved these changes

2023-05-16 13:20 UTC, merged